name: signalr_chat_plugin
description: A Flutter plugin for integrating SignalR real-time chat.
version: 1.0.4
homepage: https://github.com/go2hyder/signalr_chat_plugin
repository: https://github.com/go2hyder/signalr_chat_plugin
issue_tracker: https://github.com/go2hyder/signalr_chat_plugin/issues
documentation: https://github.com/go2hyder/signalr_chat_plugin/wiki

environment:
  sdk: ^3.7.0
  flutter: ">=1.20.0"

dependencies:
  connectivity_plus: ^6.1.4
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  rxdart: ^0.27.7
  signalr_core: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.signalr_chat_plugin
        pluginClass: SignalRChatPlugin
      ios:
        pluginClass: SignalRChatPlugin
      web:
        pluginClass: SignalRChatPlugin
        fileName: "signalr_chat_plugin.dart"